@extends('frontend.layouts.master')

@section('content')

<!-- Page Banner -->
<section class="page-banner" style="background-image: url('{{ asset('assets/images/bg3.jpg') }}'); background-size: cover; background-position: center; padding: 80px 0; position: relative;">
    <div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 75, 120, 0.7);"></div>
    <div class="container position-relative text-white">
        <h1 class="fw-bold display-5 mb-2">Automated Semen Analyser</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('frontend.index') }}" class="text-white text-decoration-none">Home</a></li>
                <li class="breadcrumb-item active text-white-50" aria-current="page">Automated Semen Analyser</li>
            </ol>
        </nav>
    </div>
</section>

<!-- Content Section -->
<section class="py-5 bg-pink-subtle">
    <div class="container py-4">
        <div class="row align-items-center">
            <div class="col-lg-7 mb-5 mb-lg-0 pe-lg-5">
                <p class="text-muted lh-lg mb-4">
                    An automated semen analyzer is a sophisticated medical device used in laboratories to analyze semen samples for various parameters related to male fertility.
                </p>
                <p class="text-muted lh-lg mb-4">
                    Here's an overview of how it works and its key features:
                </p>
                
                <h5 class="fw-bold text-dark mb-3">How it Works:</h5>
                <p class="text-muted lh-lg mb-0">
                    <span class="fw-bold text-dark">Sample Preparation:</span> The semen sample is collected and prepared for analysis according to standard laboratory procedures. This may involve diluting the sample with a special solution to ensure accurate measurements.<br>
                    <span class="fw-bold text-dark">Loading the Sample:</span> The prepared semen sample is loaded into the automated semen analyzer, typically via a sample cup or cartridge.<br>
                    <span class="fw-bold text-dark">Analysis:</span> The analyzer uses advanced technology, such as computer vision, digital imaging, and/or flow cytometry, to assess various parameters of the semen sample. These parameters may include sperm count, sperm motility (movement), sperm morphology (shape), sperm concentration, volume of semen, pH level, and other factors.<br>
                    <span class="fw-bold text-dark">Data Collection:</span> The analyzer captures images or data from the semen sample and processes it to calculate the different parameters. This data is then displayed on a computer screen or printed out for review by healthcare professionals.<br>
                    <span class="fw-bold text-dark">Interpretation:</span> The results generated by the automated semen analyzer are interpreted by healthcare professionals to assess the quality of the semen sample and provide insights into male fertility potential.
                </p>
            </div>
            <div class="col-lg-5 text-center">
                <img src="{{ asset('web-page-images/automated-semen-analyser-img.jpg') }}" class="img-fluid rounded shadow-sm w-100" style="object-fit: cover;" alt="Automated Semen Analyser">
            </div>
        </div>
    </div>
</section>

<!-- Key Features Section -->
<section class="py-5 bg-white">
    <div class="container py-4">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="fw-bold text-dark mb-3">Key Features:</h5>
                <p class="text-muted lh-lg mb-4">
                    <span class="fw-bold text-dark">Accuracy:</span> Automated semen analyzers are designed to provide accurate and reliable results, minimizing human error associated with manual semen analysis techniques.<br>
                    <span class="fw-bold text-dark">Speed:</span> These analyzers can process semen samples quickly, allowing for efficient testing and timely results.<br>
                    <span class="fw-bold text-dark">Customization:</span> Some analyzers offer customizable settings and parameters to accommodate different testing protocols and preferences.<br>
                    <span class="fw-bold text-dark">Data Management:</span> Many automated semen analyzers are equipped with data management software that allows for easy storage, retrieval, and analysis of test results. This software may also facilitate integration with laboratory information systems (LIS) for seamless record-keeping.<br>
                    <span class="fw-bold text-dark">Quality Control:</span> Built-in quality control mechanisms help ensure the accuracy and reliability of test results by monitoring instrument performance and detecting any issues or deviations.
                </p>
                <p class="text-muted lh-lg mb-0">
                    Automated semen analyzers play a crucial role in the evaluation of male fertility and are widely used in reproductive medicine clinics, fertility centers, and diagnostic laboratories to assist healthcare providers in assessing and diagnosing male infertility issues.
                </p>
            </div>
        </div>
    </div>
</section>

<style>
.bg-pink-subtle {
    background-color: #fdf5f8 !important;
}
</style>

@endsection